monolog:
  channels: ["security", "deprecation"]

  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]

    security:
      type: stream
      path: "%kernel.logs_dir%/security.log"
      level: debug
      channels: ["security"]

    deprecation:
      type: stream
      path: "%kernel.logs_dir%/deprecation.log"
      level: info
      channels: ["deprecation"]
