security:
  # Le nom du fournisseur d'utilisateurs
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  password_hashers:
    App\Entity\User:
      algorithm: auto

  # Définition du firewall pour l'authentification par formulaire
  firewalls:
    # La page de connexion
    main:
      pattern: ^/
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
      logout:
        path: app_logout
      # Le gestionnaire de sessions
      remember_me: true

  # Contrôle d'accès pour protéger les pages
  access_control:
    - { path: ^/profil, roles: ROLE_USER }
