security:
  # Fournisseur d'utilisateurs (lié à l'entité User)
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # Password hasher pour l'entité User
  password_hashers:
    App\Entity\User:
      algorithm: auto

  firewalls:
    main:
      pattern: ^/
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        csrf_token_generator: security.csrf.token_manager
        default_target_path: app_home # ou autre route après connexion
      logout:
        path: app_logout
        target: app_login
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800 # 1 semaine
        path: /
        always_remember_me: false

  access_control:
    - { path: ^/profil, roles: ROLE_USER }
