<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => '08874621f9689dfd3504746d72a8590babf1cc93593e93a56a64cd2e1ffe0e36',
  'DATABASE_URL' => 'postgresql://postgres@127.0.0.1:5432/ecoride',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'APP_TIMEZONE' => 'Europe/Paris',
  'MAILER_DSN' => 'gmail://ecoride.dev@gmail.com:teygsomvpfgblojo@default?verify_peer=0',
);
